"""Parse the app's own markdown output format back into structured data for merging."""

import re
from dataclasses import dataclass, field


@dataclass
class ParsedHighlight:
    text: str
    clip_type: str  # "highlight" or "note"
    location: str
    page: int | None


@dataclass
class ParsedChapter:
    title: str
    level: int
    highlights: list[ParsedHighlight] = field(default_factory=list)


@dataclass
class ParsedMarkdown:
    chapters: list[ParsedChapter] = field(default_factory=list)


def parse_existing_markdown(markdown_text: str) -> ParsedMarkdown:
    """Parse markdown previously generated by this app back into structured data.

    Handles the format:
        ## Chapter Title
        - "highlighted text"
          PAGE 42 · LOCATION 100-105 · HIGHLIGHT
        - note text
          ANNOTATION
    """
    result = ParsedMarkdown()
    current_chapter: ParsedChapter | None = None
    current_highlight: ParsedHighlight | None = None

    for line in markdown_text.splitlines():
        # Chapter heading: ## Title, ### Title, #### Title
        heading_match = re.match(r"^(#{2,4})\s+(.+)$", line)
        if heading_match:
            # Flush any pending highlight
            if current_highlight and current_chapter:
                current_chapter.highlights.append(current_highlight)
                current_highlight = None

            level = len(heading_match.group(1)) - 1  # ## = level 1, ### = level 2, etc.
            title = heading_match.group(2).strip()
            current_chapter = ParsedChapter(title=title, level=level)
            result.chapters.append(current_chapter)
            continue

        # Highlight line: - "text" (quoted = highlight)
        highlight_match = re.match(r'^- "(.+)"$', line)
        if highlight_match and current_chapter is not None:
            if current_highlight:
                current_chapter.highlights.append(current_highlight)
            current_highlight = ParsedHighlight(
                text=highlight_match.group(1),
                clip_type="highlight",
                location="",
                page=None,
            )
            continue

        # Note line: - text (unquoted = note)
        note_match = re.match(r"^- (.+)$", line)
        if note_match and current_chapter is not None:
            if current_highlight:
                current_chapter.highlights.append(current_highlight)
            current_highlight = ParsedHighlight(
                text=note_match.group(1),
                clip_type="note",
                location="",
                page=None,
            )
            continue

        # Metadata line (indented): PAGE 42 · LOCATION 100-105 · HIGHLIGHT
        meta_match = re.match(r"^\s{2}(.+)$", line)
        if meta_match and current_highlight:
            meta = meta_match.group(1)
            page_match = re.search(r"PAGE\s+(\d+)", meta)
            if page_match:
                current_highlight.page = int(page_match.group(1))
            # Extract location string
            loc_match = re.search(r"(LOCATION\s+\S+)", meta)
            if loc_match:
                current_highlight.location = loc_match.group(1)
            continue

    # Flush last highlight
    if current_highlight and current_chapter:
        current_chapter.highlights.append(current_highlight)

    return result
